syntax = "proto3";

package rein.v1;

option go_package = "github.com/earchibald/rein/gen/go/rein/v1;reinv1";

import "rein/v1/types.proto";

service ProjectService {
  rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse);
  rpc GetProject(GetProjectRequest) returns (GetProjectResponse);
  rpc CreateProject(CreateProjectRequest) returns (CreateProjectResponse);
  rpc UpdateProject(UpdateProjectRequest) returns (UpdateProjectResponse);
}

message ListProjectsRequest {
  PageRequest page = 1;
  ProjectStatus status = 2;
  string query = 3;
}

message ListProjectsResponse {
  repeated Project projects = 1;
  PageResponse page = 2;
}

message GetProjectRequest {
  string id = 1;
}

message GetProjectResponse {
  Project project = 1;
}

message CreateProjectRequest {
  Project project = 1;
}

message CreateProjectResponse {
  Project project = 1;
}

message UpdateProjectRequest {
  Project project = 1;
}

message UpdateProjectResponse {
  Project project = 1;
}
